spring.application.name=demo_kotlin
spring.profiles.active=dev

spring.security.user.name=admin
spring.security.user.password=your_password_here

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect