spring.datasource.portal.url=jdbc:postgresql://10.5.255.14:5432/portal_migrate
spring.datasource.portal.username=postgres
spring.datasource.portal.password=@DevTeam4321.
spring.datasource.portal.driver-class-name=org.postgresql.Driver

spring.datasource.iss.url=jdbc:postgresql://10.5.255.14:5432/iss_postgre_migrate
spring.datasource.iss.username=postgres
spring.datasource.iss.password=@DevTeam4321.
spring.datasource.iss.driver-class-name=org.postgresql.Driver