spring.application.name=demo_kotlin
spring.profiles.active=dev

spring.security.user.name=admin
spring.security.user.password=your_password_here

spring.jwt.secret=7781bffe5d36dcad4eacd7282c96a64bb719896893fd4b08511b93bc4f1f3e8afc159eec8442a9b420419cd5540915137be1693b0258f767d3fa8b863a77ba72

!Default 1 Hari (24 * 60 * 60 * 1000)
spring.jwt.expirationMs=86400000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect