spring.datasource.portal.url=jdbc:postgresql://localhost:5432/portal
spring.datasource.portal.username=postgres
spring.datasource.portal.password=12345
spring.datasource.portal.driver-class-name=org.postgresql.Driver

spring.datasource.iss.url=jdbc:postgresql://localhost:5432/iss
spring.datasource.iss.username=postgres
spring.datasource.iss.password=12345
spring.datasource.iss.driver-class-name=org.postgresql.Driver